SELECT
	company,
	SUM(CASE WHEN (value = "agile-dev") THEN 1 ELSE 0 END) as "agile-dev",
	SUM(CASE WHEN (value = "benefit-company") THEN 1 ELSE 0 END) as "benefit-company",
	SUM(CASE WHEN (value = "bonded-by-product") THEN 1 ELSE 0 END) as "bonded-by-product",
	SUM(CASE WHEN (value = "continuous-delivery") THEN 1 ELSE 0 END) as "continuous-delivery",
	SUM(CASE WHEN (value = "creative-innovative") THEN 1 ELSE 0 END) as "creative-innovative",
	SUM(CASE WHEN (value = "cross-dep") THEN 1 ELSE 0 END) as "cross-dep",
	SUM(CASE WHEN (value = "customer-first") THEN 1 ELSE 0 END) as "customer-first",
	SUM(CASE WHEN (value = "data-driven") THEN 1 ELSE 0 END) as "data-driven",
	SUM(CASE WHEN (value = "diverse-team") THEN 1 ELSE 0 END) as "diverse-team",
	SUM(CASE WHEN (value = "engages-community") THEN 1 ELSE 0 END) as "engages-community",
	SUM(CASE WHEN (value = "engineering-driven") THEN 1 ELSE 0 END) as "engineering-driven",
	SUM(CASE WHEN (value = "eq-iq") THEN 1 ELSE 0 END) as "eq-iq",
	SUM(CASE WHEN (value = "fast-paced") THEN 1 ELSE 0 END) as "fast-paced",
	SUM(CASE WHEN (value = "feedback") THEN 1 ELSE 0 END) as "feedback",
	SUM(CASE WHEN (value = "flat-organization") THEN 1 ELSE 0 END) as "flat-organization",
	SUM(CASE WHEN (value = "flex-hours") THEN 1 ELSE 0 END) as "flex-hours",
	SUM(CASE WHEN (value = "friends-outside-work") THEN 1 ELSE 0 END) as "friends-outside-work",
	SUM(CASE WHEN (value = "good-beer") THEN 1 ELSE 0 END) as "good-beer",
	SUM(CASE WHEN (value = "impressive-teammates") THEN 1 ELSE 0 END) as "impressive-teammates",
	SUM(CASE WHEN (value = "inclusive") THEN 1 ELSE 0 END) as "inclusive",
	SUM(CASE WHEN (value = "internal-mobility") THEN 1 ELSE 0 END) as "internal-mobility", 
	SUM(CASE WHEN (value = "internal-promotion") THEN 1 ELSE 0 END) as "internal-promotion",
	SUM(CASE WHEN (value = "interns") THEN 1 ELSE 0 END) as "interns",
	SUM(CASE WHEN (value = "junior-devs") THEN 1 ELSE 0 END) as "junior-devs",
	SUM(CASE WHEN (value = "light-meetings") THEN 1 ELSE 0 END) as "light-meetings",
	SUM(CASE WHEN (value = "lunch-together") THEN 1 ELSE 0 END) as "lunch-together",
	SUM(CASE WHEN (value = "many-hats") THEN 1 ELSE 0 END) as "many-hats",
	SUM(CASE WHEN (value = "new-tech") THEN 1 ELSE 0 END) as "new-tech",
	SUM(CASE WHEN (value = "office-layout") THEN 1 ELSE 0 END) as "office-layout",
	SUM(CASE WHEN (value = "open-communication") THEN 1 ELSE 0 END) as "open-communication",
	SUM(CASE WHEN (value = "open-source") THEN 1 ELSE 0 END) as "open-source",
	SUM(CASE WHEN (value = "pair-programs") THEN 1 ELSE 0 END) as "pair-programs",
	SUM(CASE WHEN (value = "parents") THEN 1 ELSE 0 END) as "parents",
	SUM(CASE WHEN (value = "personal-growth") THEN 1 ELSE 0 END) as "personal-growth",
	SUM(CASE WHEN (value = "physical-wellness") THEN 1 ELSE 0 END) as "physical-wellness",
	SUM(CASE WHEN (value = "product-driven") THEN 1 ELSE 0 END) as "product-driven",
	SUM(CASE WHEN (value = "project-ownership") THEN 1 ELSE 0 END) as "project-ownership",
	SUM(CASE WHEN (value = "psychologically-safe") THEN 1 ELSE 0 END) as "psychologically-safe",
	SUM(CASE WHEN (value = "quality-code") THEN 1 ELSE 0 END) as "quality-code",
	SUM(CASE WHEN (value = "rapid-growth") THEN 1 ELSE 0 END) as "rapid-growth",
	SUM(CASE WHEN (value = "remote-ok") THEN 1 ELSE 0 END) as "remote-ok",
	SUM(CASE WHEN (value = "retention") THEN 1 ELSE 0 END) as "retention",
	SUM(CASE WHEN (value = "risk-taking") THEN 1 ELSE 0 END) as "risk-taking",
	SUM(CASE WHEN (value = "safe-env") THEN 1 ELSE 0 END) as "safe-env",
	SUM(CASE WHEN (value = "team-oriented") THEN 1 ELSE 0 END) as "team-oriented",
	SUM(CASE WHEN (value = "worklife-balance") THEN 1 ELSE 0 END) as "worklife-balance"
FROM 
	keyvalues
GROUP BY
	company;